development:
  adapter: postgresql
  database: dailycaption_development
  min_messages: warning

test:
  adapter: postgresql
  database: dailycaption_test
  min_messages: warning

production:
  adapter: postgresql
  database: dailycaption_production
