#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'
require File.dirname(__FILE__) + "/../config/environment"

Caption
User
Vote
Comment
Photo

class FacebookDaemon
  TIMEOUT = 5

  def self.do_publisher_things args
    puts "Running FB publisher"
    puts args.inspect
    action = args.first
    args = args[1..-1]
    Timeout.timeout(TIMEOUT) { FacebookPublisher.send action, *args}
  end

  def self.do_profile_updates args
    puts "Doing profile update"
    fb_user, content, action = args
    Timeout.timeout(TIMEOUT) { fb_user.set_profile_fbml content, nil, action }
  end

  def self.update
    loop do
      begin
        while fetch = STARLING.get("facebook_actions")         
          do_publisher_things(fetch) 
        end
        while fetch = STARLING.get("facebook_profile_update") 
          do_profile_updates(fetch)  
        end
      rescue StandardError => e
        puts "**** EXCEPTION!!! fetch = #{ fetch.inspect } *** "
        puts e
        puts e.backtrace.inspect
      end
    end
  end
end

ActiveRecord::Base.logger = Logger.new STDOUT

options = {
  :app_name => "facebook_daemon",
  :ARGV => ARGV,
  :dir_mode => :normal,
  :dir => File.expand_path(File.dirname(__FILE__) + '/../log'),
  :multiple => false,
  :backtrace => true,
  :monitor => false
}

Daemons.run_proc("facebook_daemon", options) do
  loop do
    FacebookDaemon.update
    sleep 1
  end
end

